name: Deploy NodeJS App via IAM and OIDC

on:
  workflow_dispatch: # Allows manual triggering only
 # push:
  #  branches:
  #    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via IAM and OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ap-south-1
      - name: Test AWS Credentials
        run: aws sts get-caller-identity
        