name: Minimal Input and Output Demo

on:
   workflow_dispatch:
    inputs:
      user_name:
        
jobs:
  greet-and-output:
    runs-on: ubuntu-latest
    steps:
      # 1. Using the INPUT variable
      # Inputs from workflow_dispatch are accessed via ${{ inputs.<input_name> }}
      - name: Read Input and Set Output
        id: step1
        run: |
          echo "Hello, ${{ inputs.user_name }}!"

       # Outputs are accessed via ${{ steps.<step_id>.outputs.<output_name> }}  
      - name: View 
        run: echo "${{ steps.step1.outputs.out }}"
